# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-19 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('created_on', models.IntegerField()),
                ('updated_on', models.IntegerField()),
                ('deleted_on', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_token',
            },
        ),
    ]
