# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-19 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.IntegerField()),
                ('updated_on', models.IntegerField()),
                ('deleted_on', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('commonbasedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.CommonBaseData')),
                ('cart_id', models.CharField(max_length=100)),
                ('item_count', models.IntegerField(default=0)),
                ('cart_price', models.FloatField(default=0.0)),
                ('cart_status', models.CharField(max_length=20)),
                ('user_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to='usermgmt.UserTable')),
            ],
            options={
                'db_table': 'mishipay_shoppingcart',
            },
            bases=('orders.commonbasedata',),
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('commonbasedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.CommonBaseData')),
                ('product_id', models.CharField(max_length=100)),
                ('product_title', models.CharField(max_length=150)),
                ('variant_id', models.CharField(max_length=100)),
                ('product_status', models.CharField(default='added', max_length=20)),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='orders.Cart')),
            ],
            options={
                'db_table': 'mishipay_shoppingcart_products',
            },
            bases=('orders.commonbasedata',),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('commonbasedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.CommonBaseData')),
                ('order_id', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(default='offline', max_length=20)),
                ('order_status', models.CharField(default='pending', max_length=20)),
                ('order_completion_time', models.IntegerField()),
                ('order_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_orders', to='orders.Cart')),
            ],
            options={
                'db_table': 'mishipay_shopping_orders',
            },
            bases=('orders.commonbasedata',),
        ),
    ]
