# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonbasedata',
            name='deleted_on',
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
