# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='producr_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
