# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-19 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartproducts_producr_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproducts',
            old_name='producr_quantity',
            new_name='product_quantity',
        ),
    ]
