# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-19 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180719_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
    ]
